name: Aplicação Django

on: [pull_request]

jobs:
  build:
    env:
      PIPENV_NO_INHERIT: 1
      PIPENV_IGNORE_VIRTUALENVS: 1

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.4
      uses: actions/setup-python@v1
      with:
        python-version: 3.10.4
    
    - name: Install dedependencies
      run: |
        pip install pipenv
        sync pipenv --dev
    
    - name: Run automatic tests
      run: |
        pipenv run pytest diegodev
